name: Centrar Secciones TXT

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Ver archivos iniciales
      run: ls -l

    - name: Ejecutar centrado
      run: python centrar_secciones_txt.py geo.txt

    - name: Ver archivos generados
      run: ls -l

    - name: Subir resultado
      uses: actions/upload-artifact@v4
      with:
        name: resultado_centrado_txt
        path: geo_centrado.txt
