name: Procesar TXT

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Ver archivos iniciales
      run: ls -l

    - name: Ejecutar script
      run: python reenumerar_stations_KIMI_v1.py input.txt

    - name: Ver archivos generados
      run: ls -l

    - name: Subir resultados
      uses: actions/upload-artifact@v4
      with:
        name: resultados
        path: |
          input_transformado.txt
          input_stations_originales.txt
